on:
  push:
    branches:
      - main

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: "Preguntar mensaje de texto"
       run: |
         echo "Hola, escribe a continuación un texto:"
         read texto
      - name: "Mostrar mensaje de texto"
       run: |
         echo "El mensaje ingresado es: $texto"
         
