on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: "Escribe un mensaje"
        required: true

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: |
          echo "El mensaje es: ${{ github.event.inputs.mensaje }}"
